name: Build SunamoThreading

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoThreading
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoThreading/SunamoThreading.csproj

    - name: Build
      run: dotnet build SunamoThreading/SunamoThreading.csproj --configuration Release --no-restore

  test:
    name: Test SunamoThreading.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoThreading.Tests/SunamoThreading.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoThreading.Tests/SunamoThreading.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoThreading.Tests/SunamoThreading.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
